### ISSUE TITLE
doesn't on django 3.0

### ISSUE THREAD

**Issue by alejandrovelez243** [jjkester/django-auditlog#234]

**Comment by dms-cat** [comment]
To be a bit more helpful, this package is *not compatible with Django 3.0.* Specifically, ./manage.py migrate results in this error:

```text
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/src/app/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/src/app/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/src/app/.venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/src/app/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/src/app/.venv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/src/app/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/app/[redacted]/apps/users/models.py", line 3, in <module>
    from auditlog.registry import auditlog
  File "/src/app/.venv/lib/python3.6/site-packages/auditlog/registry.py", line 5, in <module>
    from django.utils.six import iteritems
ModuleNotFoundError: No module named 'django.utils.six'
```

**Comment by jjkester** [comment]
Django 3 support is coming, see #256 , #257
