### ISSUE TITLE
auditlog error in django 1.10

### ISSUE THREAD

**Issue by 029xue** [jjkester/django-auditlog#63]
Hi,

I installed django 1.10 and followed the doc to add 'auditlog' to INSTALLED_APPS and MIDDLEWARE, the migrate was doing success, however, when I start run_server, the below error shows:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0453DBB8>
Traceback (most recent call last):
  File "D:\dev\envs\django\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\dev\envs\django\lib\site-packages\django\core\management\commands\runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "D:\dev\envs\django\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "D:\dev\envs\django\lib\site-packages\django\core\management\commands\runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "D:\dev\envs\django\lib\site-packages\django\core\servers\basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "D:\dev\envs\django\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "C:\Program Files (x86)\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "xxx\wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "D:\dev\envs\django\lib\site-packages\django\core\wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "D:\dev\envs\django\lib\site-packages\django\core\handlers\wsgi.py", line 153, in __init__
    self.load_middleware()
  File "D:\dev\envs\django\lib\site-packages\django\core\handlers\base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

If I commented below line from MIDDLEWARE

```python
# 'auditlog.middleware.AuditlogMiddleware'
```

The run_server would work with no errors. 

However, after doing some actions and check audit_logentry table, nothing was recorded there.

Any ideas? Thanks very much!

**Comment by jjkester** [comment]
You need the middleware for automatic logging. What version are you running? Do you run the latest version from pypi (`pip install django-auditlog`) or are you running the latest repository version?

**Comment by 029xue** [comment]
Thanks for the quick reply.

I installed it via pypi and the installed version is 0.3.3.
( I also tried put the source in my project folder and run_server, but met the same error.).

-----
Django (1.10)
django-auditlog (0.3.3)
django-jsonfield (1.0.1)
django-suit (0.2.20)
pip (8.1.1)
psycopg2 (2.6.1)
pycodestyle (2.0.0)
setuptools (20.10.1)

**Comment by jjkester** [comment]
I have not been able to reproduce this exact behavior. However, the middleware is not yet adapted for 1.10. I have pushed changes to fix this (will merge soon), and I will be releasing 0.4.0 this evening. Could you try it again with this version?

**Comment by 029xue** [comment]
Thanks for the quick action, after upgrade to 0.4.0, it's now work like a charm.

**Comment by ra00f** [comment]
Just installed django-audit-log-0.7.0 in my django-1.11.1 (running under python 3.5.2)

_makemigration_ & _migrate_ commands run without any issue. However, when I issue _runserver_, I get the same error.

```
  self.load_middleware()
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

```
Is there any fix?

Thanks.
