### ISSUE TITLE
Migration fails with unknown migration directory

### ISSUE THREAD

**Issue by robguttman** [jjkester/django-auditlog#69]
On a new database the migrate fails as follows:
```
# python manage.py migrate 
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/migrations/loader.py", line 185, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/migrations/loader.py", line 93, in load_disk
    for name in os.listdir(directory):
OSError: [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/django_auditlog-0.3.3-py2.7.egg/auditlog/migrations'
```

My workaround was to add `zip_safe=False` to setup.py and re-install.

**Comment by jjkester** [comment]
0.3.x has some issues, especially with MySQL since I made a typo in a model definition, which became a migration at some point. Could you try again with the most recent 0.4.0 release?

**Comment by jjkester** [comment]
`zip_safe` can indeed be an issue here. Closing this because it seems fixed.
